### PR TITLE
Avoid failure in form event on customer account pages

### LINKED ISSUE #8: Call to a member function get() on null
Hi, when I want to add or edit address in frontstore in my account I'm getting this error:

screen shot 2018-03-13 at 01 06 14

Moreover I'm still not able to get this plugin works. I've override two twig templates that you are describing in the readme, but still without success. My `bitbag_invoicing_invoice` table is still empty. I'm I missing something? wkhtmltopdf installed, company data filled, billing adress in checkout step filled. Is it supposed to generate invoice after every complete step? I'm on sylius-standard 1.1.1 and invoice-plugin:dev-master. Thx!

### PR DESCRIPTION
**Pull request by juchi**
Fixes #8 

As reported, when trying to add/edit an address in the customer account, this event subscriber fails as there is no parent form defined.

### CODE REVIEW

File: src/Form/Extension/AddressTypeExtension.php [hunk 1]
```diff
@@ -64,7 +64,12 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
     {
         $builder
             ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event): void {
-                $billingAddressForm = $event->getForm()->getParent()->get('billingAddress');
+                $parentForm = $event->getForm()->getParent()
+                if ($parentForm === null) {
```
Comment (bitbager) [inline src/Form/Extension/AddressTypeExtension.php]: Could you change it to `null === $parentForm`?

Comment (juchi) [reply src/Form/Extension/AddressTypeExtension.php]: sure thing, i have updated the PR

File: src/Form/Extension/AddressTypeExtension.php [hunk 2]
```diff
@@ -64,7 +64,12 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
     {
         $builder
             ->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event): void {
-                $billingAddressForm = $event->getForm()->getParent()->get('billingAddress');
+                $parentForm = $event->getForm()->getParent()
+                if (null === $parentForm) {
+                  return;
```
Comment (bitbager) [inline src/Form/Extension/AddressTypeExtension.php]: Could you also use 4 spaces (tabulation) instead of two for the `return`? Perhaps your IDE setting has 2 spaces for tab instead of 4. If you're using PHPStorm, read this: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206332339-Tabs-and-Indents-are-2-spaces-despite-setting-at-4-spaces 🙂

Comment (juchi) [reply src/Form/Extension/AddressTypeExtension.php]: sorry, PR updated

**Comment by bitbager** [comment]
Thanks!
